package ddl

import (
	"fmt"
	"strings"

	"github.com/OWNER/qantaradb/inspector"
	"github.com/OWNER/qantaradb/planner"
)

type DDLResult struct {
	TablesDDL      map[string]string `json:"tables_ddl"`
	IndexesDDL     map[string]string `json:"indexes_ddl"`
	ForeignKeysDDL map[string]string `json:"foreign_keys_ddl"`
}

func GenerateDDL(schema *inspector.SchemaInfo, plan *planner.MigrationPlan) (*DDLResult, error) {
	result := &DDLResult{
		TablesDDL:      make(map[string]string),
		IndexesDDL:     make(map[string]string),
		ForeignKeysDDL: make(map[string]string),
	}

	planMap := make(map[string]*planner.TablePlan)
	for i := range plan.Tables {
		planMap[plan.Tables[i].SourceName] = &plan.Tables[i]
	}

	for _, t := range schema.Tables {
		tPlan, exists := planMap[t.Name]
		if !exists {
			continue // Excluded table
		}

		// 1. Generate CREATE TABLE DDL
		var colDefs []string
		var inlinePK string

		for _, col := range tPlan.Columns {
			var builder strings.Builder
			builder.WriteString(fmt.Sprintf(`"%s" %s`, col.TargetName, col.TargetType))

			// Check if primary key
			if col.SourceName == tPlan.PrimaryKeyColumn {
				if strings.Contains(strings.ToLower(col.TargetType), "int") {
					// Use identity column for serials/auto_increment representation in modern PG
					builder.WriteString(" GENERATED BY DEFAULT AS IDENTITY")
				}
				inlinePK = fmt.Sprintf(",\n  CONSTRAINT %s_pkey PRIMARY KEY (\"%s\")", tPlan.TargetName, col.TargetName)
			} else {
				if !col.IsNullable {
					builder.WriteString(" NOT NULL")
				}
			}

			// Add constraints (like CHECK)
			for _, c := range col.Constraints {
				builder.WriteString(" " + c)
			}

			colDefs = append(colDefs, "  "+builder.String())
		}

		tableDDL := fmt.Sprintf("CREATE TABLE IF NOT EXISTS \"%s\" (\n%s%s\n);", 
			tPlan.TargetName, 
			strings.Join(colDefs, ",\n"), 
			inlinePK,
		)
		result.TablesDDL[tPlan.TargetName] = tableDDL

		// 2. Generate CREATE INDEX DDLs
		var indexStatements []string
		for _, idx := range t.Indexes {
			var colList []string
			for _, colName := range idx.Columns {
				colList = append(colList, fmt.Sprintf("\"%s\"", colName))
			}

			uniqueStr := ""
			if idx.Unique {
				uniqueStr = "UNIQUE "
			}

			idxStatement := fmt.Sprintf("CREATE %sINDEX IF NOT EXISTS \"%s_%s_idx\" ON \"%s\" (%s);",
				uniqueStr, tPlan.TargetName, idx.Name, tPlan.TargetName, strings.Join(colList, ", "))
			indexStatements = append(indexStatements, idxStatement)
		}
		if len(indexStatements) > 0 {
			result.IndexesDDL[tPlan.TargetName] = strings.Join(indexStatements, "\n")
		}

		// 3. Generate CREATE FOREIGN KEY DDLs (ALTER TABLE)
		var fkStatements []string
		for _, fk := range t.ForeignKeys {
			fkStatement := fmt.Sprintf("ALTER TABLE \"%s\" ADD CONSTRAINT \"%s\" FOREIGN KEY (\"%s\") REFERENCES \"%s\" (\"%s\") ON UPDATE %s ON DELETE %s;",
				tPlan.TargetName, fk.Name, fk.ColumnName, fk.ReferencedTable, fk.ReferencedColumn, fk.UpdateRule, fk.DeleteRule)
			fkStatements = append(fkStatements, fkStatement)
		}
		if len(fkStatements) > 0 {
			result.ForeignKeysDDL[tPlan.TargetName] = strings.Join(fkStatements, "\n")
		}
	}

	return result, nil
}
